#server:
#  port: 8003 # 服务端口
#
#spring:
#  application:
#    name: service-oss # 服务名
#  profiles:
#    active: dev # 环境设置:dev、test、prod
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
## 阿里云 OSS
#aliyun:
#  oss:
#    file:
#      endpoint: oss-cn-beijing.aliyuncs.com
#      keyid: LTAI4GKkj2hskCfEkQDXzinH
#      keysecret: 6zK91yE2bn2gmbnC2jjI757Ovb6UZq
#      bucketname: javakc-student
#feign:
#  hystrix:
#    enabled: true #开启短路保护机制